spring:
  application:
    name: jpa-app
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa_db
    username: postgresql_user
    password: 12345Asd
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 24110
