version: "3"
services:
  postgress:
    image: 'postgres:latest'
    command:
      - "-d"
      - "-it postgres createdb -U postgres distcomp"
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=distcomp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ['CMD-SHELL', "pg_isready -U postgres -d distcomp"]
      interval: 10s
      timeout: 5s
      retries: 5
