spring:
  application:
    name: discussion
  datasource:
    url: jdbc:cassandra://localhost:9042/discussion_db?localdatacenter=datacenter1
    username: cassandra
    password: cassandra
    hikari:
      minimum-idle: 1
  cassandra:
    keyspace-name: discussion_db
    contact-points[0]: localhost:9042
    schema-action: recreate
    local-datacenter: datacenter1

server:
  port: 24130
